// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "mintapi/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// Minter is an autogenerated mock type for the Minter type
type Minter struct {
	mock.Mock
}

// UploadToIPFS provides a mock function with given fields: ctx, data
func (_m *Minter) UploadToIPFS(ctx context.Context, data *domain.Event) (string, error) {
	ret := _m.Called(ctx, data)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) (string, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) string); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Event) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMinter interface {
	mock.TestingT
	Cleanup(func())
}

// NewMinter creates a new instance of Minter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMinter(t mockConstructorTestingTNewMinter) *Minter {
	mock := &Minter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
