openapi: 3.0.0
info:
  title: NFTicket API
  version: 1.0.0

paths:
  /events:
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
        '400':
          description: Bad request

  /tickets:
    post:
      summary: Mint a new NFTicket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ticket'
      responses:
        '201':
          description: NFTicket minted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'
        '400':
          description: Bad request

components:
  schemas:
    Event:
      type: object
      required:
        - name
        - date
        - venue
      properties:
        name:
          type: string
          description: The name of the event
        date:
          type: string
          format: date-time
          description: The date and time of the event
        venue:
          type: string
          description: The venue where the event will take place

    EventResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the created event
        message:
          type: string
          description: A message indicating the success of the event creation

    Ticket:
      type: object
      required:
        - eventId
        - seatNumber
        - specialFeature
      properties:
        eventId:
          type: string
          format: uuid
          description: The unique identifier of the event
        seatNumber:
          type: string
          description: The seat number of the ticket
        specialFeature:
          type: array
          items:
            type: string
          description: Special characteristics received when buying this ticket

    TicketResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the minted NFTicket
        message:
          type: string
          description: A message indicating the success of the NFTicket minting
