// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "mintapi/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// Ticket is an autogenerated mock type for the Ticket type
type Ticket struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, event
func (_m *Ticket) Create(ctx context.Context, event *domain.Event) (*domain.Event, error) {
	ret := _m.Called(ctx, event)

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) (*domain.Event, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) *domain.Event); ok {
		r0 = rf(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTicket interface {
	mock.TestingT
	Cleanup(func())
}

// NewTicket creates a new instance of Ticket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTicket(t mockConstructorTestingTNewTicket) *Ticket {
	mock := &Ticket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
